### ISSUE TITLE
Use SNOMED code lists for data validation

### ISSUE THREAD

**Issue by vvcb** [LTHTR-DST/hdruk_avoidable_admissions#1]
Implement <https://github.com/MattStammers/hdruk_avoidable_admissions_collaboration_docs/issues/5>

**Comment by vvcb** [comment]
This appears to have been fixed with the documents shared by Sheffield with list of ICD10 to Ambulatory care sensitive conditions mapping as well as several other SNOMED code mappings which have now been incorporated into `feature_maps.py` and in the feature engineering and validation logic. 

[ ] Confirm that we don't need any other code lists before closing this issue

**Comment by MattStammers** [comment]
This should be closed now
