### ISSUE TITLE
Is it necessary to create a copy of the dataframe prior to passing it to validate dataframe?

### ISSUE THREAD

**Issue by MattStammers** [LTHTR-DST/hdruk_avoidable_admissions#11]
As the dataframe gets copied anyway within the validate_dataframe() function why do we create a copy of df_admcare prior to running the first validation? Isn't this just duplication?

```python 
# Create a copy of the data to fix DQ issues to avoid reloading data from source everytime
dfa = df_admcare.copy()

"Raw dataframe contains %d rows and %d columns" % dfa.shape
```

**Comment by vvcb** [comment]
Not required. 

But, if you have loaded df_admcare from a network drive over a VPN, like we have to, and make a mistake in a transformation step, this avoids having to reload from source. 

But, no you don't need to create a copy.

**Comment by MattStammers** [comment]
fair enough
