### ISSUE TITLE
Dates Range Incorrect

### ISSUE THREAD

**Issue by MattStammers** [LTHTR-DST/hdruk_avoidable_admissions#16]
As just established on the call the date range in the filter needs to be: 1st of November 2021 to 31st October 2022

I will change the mkdocs

**Comment by MattStammers** [comment]
I have now fixed this in the docs https://mattstammers.github.io/hdruk_avoidable_admissions_collaboration_docs/documentation/global_variables/

**Comment by vvcb** [comment]
Should we consider making date ranges configurable outside the core package? This will allow us to reuse the same validation schema for multiple date ranges without having to change the source code every time. For instance, if we decide to compare the current study cohort with a pre-pandemic cohort.

**Comment by MattStammers** [comment]
Probably a good idea - some kind of adjustable config would be great
