### ISSUE TITLE
Lost admission methods

### ISSUE THREAD

**Issue by MattStammers** [LTHTR-DST/hdruk_avoidable_admissions#19]
We have several patients who have no associated admission method or discharge method. We are currently losing them as a result. Could a 0 category be added for them as well?

**Comment by vvcb** [comment]
Both columns have defined values for 'unknown' in the NHS data model.

`admimeth` - <https://github.com/LTHTR-DST/hdruk_avoidable_admissions/blob/dev/avoidable_admissions/data/nhsdd.py#L75>

`dismeth` - <https://github.com/LTHTR-DST/hdruk_avoidable_admissions/blob/dev/avoidable_admissions/data/nhsdd.py#L115>  (although <https://github.com/LTHTR-DST/hdruk_avoidable_admissions/blob/dev/avoidable_admissions/features/feature_maps.py#L364> is used for mapping which also has a value for unknown)

**Comment by MattStammers** [comment]
Ok, I will close this
