### ISSUE TITLE
Snomed codes validation

### ISSUE THREAD

**Issue by ccarenzoIC** [LTHTR-DST/hdruk_avoidable_admissions#20]
Hi, I have a question regarding the validate.py script:

I've seen that some fields like _edchiefcomplaint_ don't get an "isin" validation, referencing the values from nhsdd_snomed, why is this?

Thanks!

**Comment by vvcb** [comment]
Thanks for taking the time to dig into this. The emergency care dataset validation logic has not been completed yet. Quin and I will find some time this week to do this. 

Happy to take contributions.  If you are familiar with git workflow, then please fork, clone your work, develop and create a pull request. Alternatively, happy to have code snippets as responses to issues.

**Comment by MattStammers** [comment]
When do we get the next release 🥇 
:octocat:

**Comment by vvcb** [comment]
@ccarenzoIC , please see https://github.com/LTHTR-DST/hdruk_avoidable_admissions/pull/21#issuecomment-1421571369 and let me know what you think. 

@MattStammers, will aim 0.2.0 with ED data pipeline tomorrow after conferring with @ccarenzoIC  and @quindavies. We want to test this against LTH data before tagging it as a release.

**Comment by vvcb** [comment]
A number of challenges remain with SNOMED code validation - see #27 as well.

**Comment by vvcb** [comment]
Closing as multiple PRs have addressed this. Some challenges remain but none that can be readily solved through this libary.
