### ISSUE TITLE
Test and resolve dependency conflicts

### ISSUE THREAD

**Issue by vvcb** [LTHTR-DST/hdruk_avoidable_admissions#3]
The environment.yml file currently pins `Python>=3.11`. This is the latest version of Python released in October 2022 with significant [performance improvements](https://docs.python.org/3/whatsnew/3.11.html#summary-release-highlights). Other major libraries have started adding support. However, certain libraries such as `pandas-profiling` do not work yet.

As the project progresses and there is a need for other libraries such as `sklearn`, `scipy`, `statsmodels`, etc., we are likely to run into dependency issues and may have to downgrade to `python=3.10*` or `python=3.9.*` even.

It will be very useful if analysts using Python to test and feedback.

**Comment by MattStammers** [comment]
We in Southampton recommend moving all environments to python 3.10. That is what we are using

**Comment by MattStammers** [comment]
some of the commit hooks break if you use python 3.10 but they can be deactivated as needed

**Comment by vvcb** [comment]
Closing as no issues have been reported so far.
