### ISSUE TITLE
Validator not picking up ACSC's for avoidable admissions

### ISSUE THREAD

**Issue by MattStammers** [LTHTR-DST/hdruk_avoidable_admissions#33]
I have tried overwriting all the first diagnoses with codes like cellulitis '128045006' and the validator is not picking these up flagging everything as non-ACSC on the final step.

**Comment by vvcb** [comment]
@MattStammers , thank you for reporting this.

Can you please add some more details to the first post to describe how one may replicate this problem? Based on the WhatsApp messages, I understand that there may be a problem with the ACSC mapping of `diag_01` variable in the _admitted care dataset_. 

If this is correct, then this will affect most of the generated tables. 

There may be a problem with how this feature is built. Would you mind having a look at the following sections of code to see what may be broken?

- <https://github.com/LTHTR-DST/hdruk_avoidable_admissions/blob/dev/avoidable_admissions/features/admitted_care_features.py#L100-L110>
- <https://github.com/LTHTR-DST/hdruk_avoidable_admissions/blob/dev/avoidable_admissions/features/feature_maps.py#L510-L525>

And definitely worth checking the Sheffield mapping spec google sheet - link can be reconstructed from the second code section above. `feature_maps.py` directly reads this google sheet and uses the data for the mapping.

Happy to look at a PR if there is a bug at this end.

**Comment by MattStammers** [comment]
Right @georgm8 has looked at the code and found the issue

![MicrosoftTeams-image](https://user-images.githubusercontent.com/67735183/221156642-e4e564d8-9958-4a52-ae52-2f8090ae415d.png)

our ICD codes had a full stop in them which was not being picked up. Presently it was replacing this with a space. Either we need consensus on the format of the ICD10 codes or a regex validator to be added. I think @georgm8 is happy to do this?

**Comment by georgm8** [comment]
Happy to create a validator once we have consensus on how we want the ICD-10 codes to look

**Comment by vvcb** [comment]
The Sheffield spec uses a period `.` after the first three characters if there are more than 3 characters. At LTH, we don't have a `.` in the raw data and found that the simplest thing to do was to remove this from the Sheffield spec google sheet. 

For _acute_admits_ dataset, 

- Sheffield mapping: <https://docs.google.com/spreadsheets/d/1M3uS6qh3d9OY31gFxy8858ZxBiFjGE_Y/edit> 
- Code: <https://github.com/LTHTR-DST/hdruk_avoidable_admissions/blob/dev/avoidable_admissions/features/feature_maps.py#L522>

My view is that we get rid of the `.` to keep things simple.

~Just found that we are not doing this in the ECDS dataset.~

- Sheffield mapping: <https://docs.google.com/spreadsheets/d/1Jsx4Am9a3Hvv7VJwIFb4z4_oV7zXL39e/>.
- ~Code that _may_ need modifying: <https://github.com/LTHTR-DST/hdruk_avoidable_admissions/blob/dev/avoidable_admissions/features/feature_maps.py#L542-L543>~

Ignore this as the ECDS mapping is SNOMED to category and should not be affected. The ECDS mapping google docs however also has ICD codes in it and worth exploring further.

**Comment by vvcb** [comment]
@MattStammers , feel free to close this issue if #35 by @georgm8 addresses this.

@quindavies , we will have to run the new changes in #35 against out admitted care dataset and make sure there are no surprises.
