### ISSUE TITLE
Missing grouping of Chief Complaint

### ISSUE THREAD

**Issue by ccarenzoIC** [LTHTR-DST/hdruk_avoidable_admissions#36]
Hi,

The grouping of chief complaints according to the [Data Processing V2 document](https://docs.google.com/document/d/1uvywYJrwYv7K3jMkpPPj0OOdTove9yXHPQeydD406fQ/edit#heading=h.opxu6l17ve7i ) is missing. 

Happy to contribute if this is not yet being developed.

Thanks,

**Comment by vvcb** [comment]
Thank you very much @ccarenzoIC. That will be much appreciated. I think Sheffield are working on fixing (or may have already fixed) some of the issues with the SNOMED coding. 

But a PR based on [Chief_Complaint_Coding_V2](https://docs.google.com/spreadsheets/d/18XbVmWJsccACoTDFd8EBeslKPtsPApqi/edit#gid=589962562) will be awesome. We can always tweak it if we need to.

Tagging @MattStammers  and @georgm8 to make sure that they are not working on this as well. I don't think they are.

**Comment by MattStammers** [comment]
we are also working on this @ccarenzoIC @vvcb

**Comment by MattStammers** [comment]
should hopefully be done very soon

**Comment by MattStammers** [comment]
we have added a pull for chief complaint

**Comment by ccarenzoIC** [comment]
https://github.com/LTHTR-DST/hdruk_avoidable_admissions/pull/40
