### ISSUE TITLE
Create a pyproject.toml file

### ISSUE THREAD

**Issue by vvcb** [LTHTR-DST/hdruk_avoidable_admissions#7]
The current project setup requires building a conda environment and then installing this module using `pip install -e .` for development purposes.

However, for just using the package rather than developing it, it will be good to have a `pip install` option even if installing directly from github. 

The current `setup.py` file does not list the correct dependencies. Ideally, we should be using a `pyproject.toml` file for this.

**Comment by MattStammers** [comment]
The pip install to github is working and seems to have the core dependencies for working in a jupyter-notebook. I only had issues in VScode when I was not logged on as an administrator

**Comment by vvcb** [comment]
Fixed by 8dc40c0204dba0c9b4c4728d4c787d19af1d681e
