### ISSUE TITLE
SNOMED codes for edarrivalmode in specification are incorrect

### ISSUE THREAD

**Issue by vvcb** [LTHTR-DST/hdruk_avoidable_admissions#9]
Many of the SNOMED codes for `edarrivalmode` in the data specification document are not valid codes. None of the ones starting with 20 appear to be valid. Needs to be checked by lead site.

From the specification document:

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-2a129ad1-7fff-706c-6008-322033e3bb39"><div dir="ltr" style="margin-left:0pt;" align="left">

SNOMED CODE | ECDS Description | Arrival Mode
-- | -- | --
1048071000000103 | Patient arranged own transport / walk-in | Walk-In
1048061000000105 | Arrival by public transport | Walk-In
2018310000 | Emergency road ambulance | Ambulance
2018350000 | Emergency road ambulance with medical escort | Ambulance
2018370000 | Non-emergency road ambulance | Ambulance
2018510000 | Helicopter | Ambulance
2018550000 | Fixed wing / medical repatriation by air | Other
2018810000 | Custodial services: prison / detention centre transport | Other
2018910000 | Police Transport | Other

</div></b>
</body>
</html>

LTH counts of `edarrivalmode`:
```
1048071000000103    34630
1048031000000100    23018
1048061000000105     2085
1048001000000106      709
1047991000000102      149
1048021000000102      133
1048051000000107       68
1048041000000109        7
1048081000000101        6

missing                         23

```

**Comment by quindavies** [comment]
Noticed that too, the mapping that I did was based on the ECDS arrival mode reference set. Happy to correct if needed though.

https://termbrowser.nhs.uk/?perspective=full&conceptId1=999002981000000107

**Comment by vvcb** [comment]
Close and track #27 instead
